In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

In [7]:
df = pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [8]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [12]:
df.dropna(inplace=True)

In [13]:
movies = df[df['type'] == 'Movie']
movies = movies.reset_index(drop=True)

In [14]:
movies['combined'] = (
    movies['description'] + ' ' +
    movies['listed_in'] + ' ' +
    movies['cast'] + ' ' +
    movies['director']
)

In [15]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['combined'])

In [16]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [17]:
movie_index = pd.Series(movies.index, index=movies['title']).drop_duplicates()

In [18]:
def recommend_movies(movie_name, num_recommendations=5):
    if movie_name not in movie_index:
        return "Movie not found in dataset"
    
    idx = movie_index[movie_name]
    similarity_scores = list(enumerate(cosine_sim[idx]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    similarity_scores = similarity_scores[1:num_recommendations+1]
    
    movie_indices = [i[0] for i in similarity_scores]
    return movies[['title', 'listed_in']].iloc[movie_indices]

In [19]:
recommend_movies("Inception")

                 title                                listed_in
3508             Brick            Independent Movies, Thrillers
3434  Before the Flood                            Documentaries
66       Mars Attacks!  Comedies, Cult Movies, Sci-Fi & Fantasy
340     Sniper: Legacy                       Action & Adventure
3695       Dragonheart     Action & Adventure, Sci-Fi & Fantasy

In [21]:
movie_name = input("Enter movie name: ")
recommend_movies(movie_name)

Enter movie name:  Sniper: Legacy

                      title                                          listed_in
513   Sniper: Ghost Shooter                                 Action & Adventure
324       Company of Heroes                         Action & Adventure, Dramas
150               Inception    Action & Adventure, Sci-Fi & Fantasy, Thrillers
3293           Act of Valor                                 Action & Adventure
1626     Doom: Annihilation  Action & Adventure, Horror Movies, Sci-Fi & Fa...

In [22]:
pip install streamlit

Requirement already satisfied: streamlit in c:\users\sainath\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\sainath\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\sainath\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\sainath\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\sainath\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\sainath\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\sainath\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\sainath\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sainath\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sainath\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sainath\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sainath\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sainath\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sainath\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sainath\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sainath\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\sainath\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\sainath\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\sainath\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\sainath\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sainath\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [23]:
import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv("netflix_titles.csv")
df.fillna('', inplace=True)
movies = df[df['type'] == 'Movie'].reset_index(drop=True)

movies['combined'] = movies['description'] + ' ' + movies['listed_in'] + ' ' + movies['cast'] + ' ' + movies['director']

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['combined'])
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

movie_index = pd.Series(movies.index, index=movies['title']).drop_duplicates()

def recommend(movie):
    if movie not in movie_index:
        return []
    idx = movie_index[movie]
    scores = list(enumerate(cosine_sim[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:6]
    return movies['title'].iloc[[i[0] for i in scores]]

st.title("Movie Recommendation System")

movie_name = st.text_input("Enter movie name")

if st.button("Recommend"):
    result = recommend(movie_name)
    for m in result:
        st.write(m)

2025-12-23 18:53:50.384 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.686
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\SAINATH\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-12-23 18:53:50.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.700 Session state does not function when running a script without `streamlit run`
2025-12-23 18:53:50.702 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.709 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.711 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-23 18:53:50.715 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.